### ISSUE TITLE
Style the handlebars files

### ISSUE THREAD

**Issue by Myhyun** [Q118/jmsj#9]

**Comment by jessicablank** [comment]
- [ ] Update background color to match theme on Playlist and Search Pages

**Comment by median-man** [comment]
Create style and layout for handlebars views as follows:

## Playlist view

- [ ] Navbar complete including brand and links to home page, search, and logout

- [ ] Not watched yet section has 3 fake shows. Each show should display the show name, platform name,  currently watching button

- [ ] Current watching section has 3 fake shows. Each show should display the show name, platform name, watched button.

- [ ] Watched section has 2 fake shows. Each show should display the show name, platform name.

- [ ] BUttons don't need to be functional yet. Just work on markup, styling, layout etc.
